
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anujgupta09/temporary.git
    targetRevision: HEAD
    path: ws
  destination:
    server: https://kubernetes.default.svc
    namespace: myargo

  syncPolicy:
    syncOptions:
    - CreateNameSpace=true

    automated:
      selfHeal: true
      prune: true

