
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  labels:
  name: deployment-backend9799
spec:
  replicas: 34
  selector:
    matchLabels:
      app: backend9799
  template:
    metadata:
      namespace: production
      labels:
        app: backend9799
    spec:
      containers:
      - name: backend9799
        image: 302315242071.dkr.ecr.ap-south-1.amazonaws.com/lineupxbackend9799:{{ .Values.IMAGE_VERSION }}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: service-backend9799
spec:
  type: NodePort
  selector:
    app: backend9799
  ports:
    - port: 3000
      targetPort: 3000
---
