---
apiVersion: v1
kind: Namespace
metadata:
  name: 9799-lineupx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 9799-lineupx
  labels:
  name: deployment-backend9799
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend9799
  template:
    metadata:
      namespace: 9799-lineupx
      labels:
        app: backend9799
    spec:
      containers:
      - name: backend9799
        image: 302315242071.dkr.ecr.ap-south-1.amazonaws.com/lineupxbackend9799:v4
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: 9799-lineupx
  name: service-backend9799
spec:
  type: NodePort
  selector:
    app: backend9799
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 9799-lineupx
  labels:
  name: deployment-httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      namespace: 9799-lineupx
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: 9799-lineupx
  name: service-httpd
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
---